"""Variable-length generation (docs/01-design.md §7, D1; stop rule revised D11).

Stop rule (D11, 2026-09-13 用户拍板): **space-like word-boundary stop first** —
commit the predicted byte stream up to and including the first space-like byte
(space/\\t/\\n/\\r); **entropy interrupt is only a fallback** (theta_fallback):
if H(delta) exceeds it before any space-like byte, cut the commit just before
that position (the model is too uncertain to trust further bytes). The pure
entropy-stop scheme (BLT philosophy, stop_mode="entropy") is kept for
comparison but is no longer the default: word boundaries are LOW-entropy
(determined) positions, so pure H>theta stopping could never land on them.

Loop: backbone gives h at the last patch -> one batched head forward yields
the 256-way distribution and entropy H(delta) for every delta in 1..m_max ->
commit per the stop rule -> the committed span becomes the next patch via the
Set Transformer encoder -> repeat.

Naive by design: the backbone is recomputed over all patch latents every step
(O(T^2), no KV cache) — fine for smoke-scale evaluation; KV caching is a v2 item.
"""
from __future__ import annotations

from typing import Any

import torch
import torch.nn.functional as F

from .data import PAD_ID
from .segment import Segmenter

SPACE_LIKE = frozenset({9, 10, 13, 32})


@torch.no_grad()
def generate(
    model,
    prompt: str | bytes,
    segmenter: Segmenter,
    cfg,
    max_commits: int = 32,
    theta_stop: float = 1.5,
    m_max: int | None = None,
    temperature: float = 0.0,
    device: str = "cuda",
    stop_mode: str = "space",
    theta_fallback: float = 3.5,
) -> dict[str, Any]:
    """Returns {text, spans, entropies}: generated bytes, committed span lengths,
    and per-step entropy arrays (for diagnostics)."""
    m_max = m_max or cfg.infer.m_max
    l_max = cfg.segment.l_max
    if isinstance(prompt, str):
        prompt = prompt.encode("utf-8")
    patches = [list(u) for u in segmenter.segment_bytes(prompt)]
    out = bytearray(prompt)
    spans: list[int] = []
    entropies: list[list[float]] = []

    for _ in range(max_commits):
        S = len(patches)
        byte_ids = torch.full((1, S, l_max), PAD_ID, dtype=torch.long)
        pad_mask = torch.ones(1, S, l_max, dtype=torch.bool)
        for j, pb in enumerate(patches):
            L = min(len(pb), l_max)
            byte_ids[0, j, :L] = torch.tensor(pb[:L], dtype=torch.long)
            pad_mask[0, j, :L] = False
        byte_ids, pad_mask = byte_ids.to(device), pad_mask.to(device)

        with torch.autocast("cuda", dtype=torch.bfloat16, enabled=cfg.train.bf16):
            h = model(byte_ids, pad_mask)[:, -1]  # (1, d)
            delta = torch.arange(m_max, device=device)
            logits = model.head(h.expand(m_max, -1), delta).float()
        logp = F.log_softmax(logits, dim=-1)
        p = logp.exp()
        H = -(p * logp).sum(-1)  # (m_max,) nats
        entropies.append([round(v, 3) for v in H.cpu().tolist()])

        if temperature and temperature > 0:
            nb = torch.multinomial(p / temperature, 1).squeeze(-1)
        else:
            nb = p.argmax(dim=-1)
        nb_list = nb.cpu().tolist()

        if stop_mode == "entropy":  # legacy BLT-style pure entropy stop (comparison only)
            over = (H > theta_stop).nonzero(as_tuple=True)[0]
            stop_at = int(over[0]) if over.numel() else m_max
            commit = min(max(stop_at, 1), m_max)
        else:  # D11: space-like boundary stop, entropy interrupt as fallback
            commit = m_max
            for i, b in enumerate(nb_list):
                if H[i].item() > theta_fallback:
                    commit = min(max(i, 1), m_max)  # cut before the uncertain byte
                    break
                if b in SPACE_LIKE:
                    commit = i + 1  # natural stop: include the space-like byte
                    break

        new_bytes = nb_list[:commit]
        out.extend(new_bytes)
        spans.append(len(new_bytes))
        patches.append(new_bytes)  # committed span = the next patch

    return {"text": bytes(out), "spans": spans, "entropies": entropies}
