"""Entropy-stopped variable-length generation (docs/01-design.md §7, D1/D5).

Loop: backbone gives h at the last patch -> one batched head forward yields
the 256-way distribution and entropy H(delta) for every delta in 1..m_max ->
commit the prefix up to the first H(delta) > theta_stop (always >= 1 byte to
guarantee progress) -> the committed span becomes the next patch via the Set
Transformer encoder -> repeat.

Naive by design: the backbone is recomputed over all patch latents every step
(O(T^2), no KV cache) — fine for smoke-scale evaluation; KV caching is a v2 item.
"""
from __future__ import annotations

from typing import Any

import torch
import torch.nn.functional as F

from .data import PAD_ID
from .segment import Segmenter


@torch.no_grad()
def generate(
    model,
    prompt: str | bytes,
    segmenter: Segmenter,
    cfg,
    max_commits: int = 32,
    theta_stop: float = 1.5,
    m_max: int | None = None,
    temperature: float = 0.0,
    device: str = "cuda",
) -> dict[str, Any]:
    """Returns {text, spans, entropies}: generated bytes, committed span lengths,
    and per-step entropy arrays (for diagnostics)."""
    m_max = m_max or cfg.infer.m_max
    l_max = cfg.segment.l_max
    if isinstance(prompt, str):
        prompt = prompt.encode("utf-8")
    patches = [list(u) for u in segmenter.segment_bytes(prompt)]
    out = bytearray(prompt)
    spans: list[int] = []
    entropies: list[list[float]] = []

    for _ in range(max_commits):
        S = len(patches)
        byte_ids = torch.full((1, S, l_max), PAD_ID, dtype=torch.long)
        pad_mask = torch.ones(1, S, l_max, dtype=torch.bool)
        for j, pb in enumerate(patches):
            L = min(len(pb), l_max)
            byte_ids[0, j, :L] = torch.tensor(pb[:L], dtype=torch.long)
            pad_mask[0, j, :L] = False
        byte_ids, pad_mask = byte_ids.to(device), pad_mask.to(device)

        with torch.autocast("cuda", dtype=torch.bfloat16, enabled=cfg.train.bf16):
            h = model(byte_ids, pad_mask)[:, -1]  # (1, d)
            delta = torch.arange(m_max, device=device)
            logits = model.head(h.expand(m_max, -1), delta).float()
        logp = F.log_softmax(logits, dim=-1)
        p = logp.exp()
        H = -(p * logp).sum(-1)  # (m_max,) nats
        entropies.append([round(v, 3) for v in H.cpu().tolist()])

        over = (H > theta_stop).nonzero(as_tuple=True)[0]
        stop_at = int(over[0]) if over.numel() else m_max  # first high-entropy delta
        commit = min(max(stop_at, 1), m_max)  # always commit >= 1 byte
        if temperature and temperature > 0:
            nb = torch.multinomial((p[:commit] / temperature), 1).squeeze(-1)
        else:
            nb = p[:commit].argmax(dim=-1)
        new_bytes = nb.cpu().tolist()
        out.extend(new_bytes)
        spans.append(len(new_bytes))
        patches.append(new_bytes)  # committed span = the next patch

    return {"text": bytes(out), "spans": spans, "entropies": entropies}
